export { CommentInterface as comment } from './reddit-interface'
import { comment } from '.'
export interface comments {
	kind: string,
	data: {
		after: string,
		dist: number,
		modhash: string,
		geo_filter: string,
		children: [
			{
				kind: string,
				data: comment
			}
		],
		before?: null
	}
}
/*
export interface comment {
	link_url: string,
	subreddit_id: string,
	approved_at_utc?: string,
	author_is_blocked: boolean,
	comment_type?: string,
	link_title: string,
	mod_reason_by?: string,
	banned_by?: string,
	ups: number,
	num_reports: number,
	author_flair_type: string,
	total_awards_received: number,
	subreddit: string,
	link_author: string,
	distinguished?: string,
	likes?: string,
	replies: string,
	user_reports: [],
	saved: boolean,
	id: string,
	banned_at_utc?: string,
	mod_reason_title?: string,
	gilded: number,
	archived: boolean,
	collapsed_reason_code?: string,
	no_follow: boolean,
	spam: boolean,
	num_comments: number,
	can_mod_post: boolean,
	created_utc: number,
	send_replies: boolean,
	parent_id: string,
	score: number,
	author_fullname: string,
	over_18: boolean,
	report_reasons: [],
	approved_by?: string,
	controversiality: number,
	body: string,
	edited: boolean,
	gildings: {},
	author_flair_css_class: string,
	author_flair_background_color: string,
	is_submitter: boolean,
	downs: number,
	author_flair_richtext: [
		{
			e: string,
			t: string
		}
	],
	author_patreon_flair: boolean,
	body_html: string,
	removal_reason?: string,
	collapsed_reason?: string,
	link_id: string,
	associated_award?: string,
	stickied: boolean,
	author_premium: boolean,
	can_gild: boolean,
	top_awarded_type?: string,
	unrepliable_reason?: string,
	approved: boolean,
	author_flair_text_color: string,
	score_hidden: boolean,
	permalink: string,
	subreddit_type: string,
	link_permalink: string,
	name: string,
	created: number,
	subreddit_name_prefixed: string,
	author_flair_text: string,
	removed: boolean,
	author: string,
	collapsed: boolean,
	awarders: [],
	all_awardings: [],
	locked: boolean,
	ignore_reports: boolean,
	collapsed_because_crowd_control?: string,
	mod_reports: [],
	quarantine: boolean,
	mod_note?: string,
	treatment_tags: [],
	author_flair_template_id: string
}*/